#ifndef __RFC_1700_H__
#define __RFC_1700_H__

enum dhcp_htype {
    ETHERNET = 1,
    EXPERIMENTAL_ETHERNET = 2,
    AMATEUR_RADIO_AX_24 = 3,
    PROTEON_PRONET_TOKEN_RING = 4,
    CHAOS = 5,
    IEEE_802 = 6,
    ARCNET = 7,
    HYPERCHANNEL = 8,
    LANSTAR = 9,
    AUTONET_SHORT_ADDRESS = 10,
    LOCALTALK = 11,
    LOCALNET = 12,
    ULTRA_LINK = 13,
    SMDS = 14,
    FRAME_DELAY = 15,
    ASYNC_TRANSMITION_MODE = 16,
    HDLC = 17,
    FIBRE_CHANNEL = 18,
    ASYNC_TRANSMITION_MODE_2 = 19,
    SERIAL_LINE = 20,
    ASYNC_TRANSMITION_MODE_3 = 21
};

#endif // !__RFC_1700_H__
