name: CI

on:
  push:  # Run the workflow on every push to any branch
    branches:
      - '**'
  pull_request:  # Also run the workflow on every pull request
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: gcc
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          mkdir $GITHUB_WORKSPACE/include
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/include::$LD_LIBRARY_PATH
          apt-get update -qy
          apt-get install -y cmake 

      - name: Compile dependencies
        run: make deps

      - name: Compile projects
        run: make projects

      - name: Compile tests
        run: make test __PIPELINE_BUILD=y

